
const companyData = [
  {
    name: "Global Tech Solutions",
    ceo: "Nichol James",
    revenue: "€245M",
    profit: "+€35M",
    ebitda: "+€25M",
    margin: "28.5%",
    marginPositive: true,
    insights: ["Strong Growth", "Growth Leader : Tech"],
  },
  {
    name: "Tech Innovation Corp",
    ceo: "Alex Morgan",
    revenue: "€342M",
    profit: "+€40M",
    ebitda: "+€5M",
    margin: "22.3%",
    marginPositive: true,
    insights: ["High Profitability", "Good Growth"],
  },
  {
    name: "NexGen Innovations",
    ceo: "Jordan Lee",
    revenue: "€224M",
    profit: "-€10M",
    ebitda: "+€12M",
    margin: "18.5%",
    marginPositive: true,
    insights: ["Robust Expansion", "Tech sector leader"],
  },
  {
    name: "Synergy Solutions",
    ceo: "Martin Luthar",
    revenue: "€85M",
    profit: "+€32M",
    ebitda: "+€20M",
    margin: "13.6%",
    marginPositive: false,
    insights: ["Poor Expansion", "Loss making"],
  },
  {
    name: "Vertex Global Services",
    ceo: "Jatin Mehta",
    revenue: "€120M",
    profit: "-€12M",
    ebitda: "+€10M",
    margin: "5.4%",
    marginPositive: true,
    insights: ["Restructuring Phase", "Strategic Pivot"],
  },
  {
    name: "Nordic Systems AB",
    ceo: "Jay Dublin",
    revenue: "€310M",
    profit: "-€2M",
    ebitda: "+€15M",
    margin: "0.6%",
    marginPositive: false,
    insights: ["Struggling sector: Marketing", "Loss-Making Company"],
  },
  {
    name: "Quantum Computing Inc",
    ceo: "Jay Dublin",
    revenue: "€90M",
    profit: "+€15M",
    ebitda: "+€2M",
    margin: "30.1%",
    marginPositive: true,
    insights: ["Market Leader", "Cost Optimization"],
  },
  {
    name: "Pinnacle Systems",
    ceo: "Jay Dublin",
    revenue: "€275M",
    profit: "+€50M",
    ebitda: "+€6M",
    margin: "19.8%",
    marginPositive: true,
    insights: ["Reliable Returns", "Strong Balance Sheet"],
  },
  {
    name: "Pacific Solutions Ltd",
    ceo: "Jay Dublin",
    revenue: "€400M",
    profit: "-€5M",
    ebitda: "+€9M",
    margin: "16.2%",
    marginPositive: true,
    insights: ["Solid Financial Track Record", "Investor-Friendly"],
  },
  {
    name: "Innovatech Dynamics",
    ceo: "Jay Dublin",
    revenue: "€90M",
    profit: "+€20M",
    ebitda: "+€20M",
    margin: "9.7%",
    marginPositive: false,
    insights: ["Liquidity Crunch", "High Overheads"],
  },
  {
    name: "Technosphere Groups",
    ceo: "Jay Dublin",
    revenue: "€230M",
    profit: "+€15M",
    ebitda: "+€20M",
    margin: "3.5%",
    marginPositive: true,
    insights: ["Reliable Returns", "Strength : Services"],
  },
];

export default companyData;
